### ISSUE TITLE
App becomes unavailable after a few days

### ISSUE THREAD

**Issue by yidan** [steventroughtonsmith/tvOSBrowser#17]
I modified and installed the browser app and it worked great! But it becomes unavailable after a few days. Any clue on what the cause is?

**Comment by jerrebm** [comment]
Same issue here..

**Comment by yidan** [comment]
@egyptik Are you enrolled in Apple Developer Program? If not, the temporary permission will expire in a few days and you have to reinstall the app.

**Comment by jerrebm** [comment]
@yidan Ahh okay, I'm not. Thanks! :)
